spring.application.name=PuntoyComaBackend

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.muozenxfcbddxpjnbhsx
spring.datasource.password=PuntoyComa%123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Activa/desactiva la UI de Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha




ip.frontend=http://localhost:4200

jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

spring.datasource.hikari.connection-timeout=5000
spring.jpa.properties.javax.persistence.query.timeout=5000

# Supabase Storage Configuration
supabase.url=https://muozenxfcbddxpjnbhsx.supabase.co